# Analysis Cryptocurrencies

## Problems
Cryptocurrencies  merupakan mata uang digital yang memiliki nilai yang tinggi <br>
dan Cryptocurrencies adalah mata uang masa depan, namun seperti yang kita ketahui. <br>
Cryptocurrencies mempunyai rekor nilai yang naik turun dan susah di prediksi. <br>
<ul>
<li>Apa saja yang mempengaruhi nilai dari Cryptocurrencies </li>
<li>Apakah Bitcoin akan tetap mendominasi pasar crypto dalam beberapa bulan ke depan?</li>
</ul>

## Dataset
Untuk Dataset saya memakai dataset yang disediakan di kaggle. <br>
saya doawnload pada link ini <a href = "https://www.kaggle.com/datasets/nulldata/cryptocurrencies-price?resource=download">Dataset</a>

## Import Libary yang dibutuhkan

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sbn
from sklearn.preprocessing import  OneHotEncoder

## Dataset

In [2]:
url = "/content/drive/MyDrive/cryptocurrencies_prices.csv"
crypto = pd.read_csv(url)
crypto

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,...,USD_percent_change_1h,USD_percent_change_24h,USD_percent_change_7d,USD_percent_change_30d,USD_percent_change_60d,USD_percent_change_90d,USD_market_cap,USD_market_cap_dominance,USD_fully_diluted_market_cap,USD_last_updated
0,1,Bitcoin,BTC,bitcoin,9175,2013-04-27T18:30:00Z,NaN,2.100000e+07,1.896551e+07,1.896551e+07,...,0.580256,0.213243,-14.028846,7.930691,-26.385180,-33.283505,7.182518e+11,42.2047,7.953008e+11,2022-02-22T14:00:00Z
1,1027,Ethereum,ETH,ethereum,5516,2015-08-06T18:30:00Z,NaN,NaN,1.196883e+08,1.196883e+08,...,0.362044,-1.194502,-16.424475,7.368335,-36.563099,-38.249109,3.114206e+11,18.2992,3.114206e+11,2022-02-22T14:00:00Z
2,825,Tether,USDT,tether,28381,2015-02-24T18:30:00Z,NaN,NaN,7.935471e+10,8.206470e+10,...,-0.004358,0.005424,-0.005421,0.030958,0.043305,0.051258,7.939648e+10,4.6670,8.210789e+10,2022-02-22T14:00:00Z
3,1839,BNB,BNB,bnb,710,2017-07-24T18:30:00Z,NaN,1.651168e+08,1.651168e+08,1.651168e+08,...,0.950867,-0.130426,-14.620480,-0.008440,-32.687530,-36.709803,6.088951e+10,3.5779,6.088951e+10,2022-02-22T14:00:00Z
4,3408,USD Coin,USDC,usd-coin,3082,2018-10-07T18:30:00Z,NaN,NaN,5.272271e+10,5.272271e+10,...,0.105669,0.039643,0.085461,0.053623,0.043420,-0.092089,5.273969e+10,3.0990,5.273969e+10,2022-02-22T14:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,8416,Finxflo,FXF,finxflo,7,2021-02-08T18:30:00Z,NaN,1.500000e+08,8.379417e+07,1.500000e+08,...,0.168810,-2.399785,-16.900859,-5.834394,-36.867538,-65.765388,8.568652e+06,0.0000,1.533875e+07,2022-02-22T14:00:00Z
996,13969,Phoenix Global (new),PHB,phoenix-global-new,3,2021-11-05T08:33:00Z,NaN,NaN,3.713677e+07,3.713677e+07,...,1.380285,-1.889863,-20.239260,-18.937211,-53.767721,-64.225421,8.547035e+06,0.0000,8.547035e+06,2022-02-22T14:00:00Z
997,9958,SafeMoon Inu,SMI,safemoon-inu,9,2021-05-19T18:30:00Z,NaN,1.000000e+12,1.000000e+12,1.000000e+12,...,-0.026369,-9.745731,-40.414209,40.439556,-40.610156,-69.685962,8.535532e+06,0.0000,8.535532e+06,2022-02-22T14:00:00Z
998,4769,EOS Force,EOSC,eos-force,4,2019-10-09T18:30:00Z,NaN,NaN,9.640701e+08,1.000000e+09,...,0.369962,-4.215316,-7.531283,9.707404,-41.835106,-56.039771,8.521183e+06,0.0005,8.838759e+06,2022-02-22T14:00:00Z
999,5228,Galatasaray Fan Token,GAL,galatasaray-fan-token,7,2020-06-07T18:30:00Z,NaN,NaN,3.507572e+06,1.000000e+07,...,-0.105354,-4.040696,-12.547196,-1.605722,-49.883356,-62.117431,8.513606e+06,0.0000,2.427208e+07,2022-02-22T14:00:00Z

## EDA Ekspor Data Analys

Disini saya akan melihat jumlah data, colum data dan melihat berapa data yang memiliki type data object dan numeric

In [3]:
crypto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 32 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                1000 non-null   int64
 1   name                              1000 non-null   object
 2   symbol                            1000 non-null   object
 3   slug                              1000 non-null   object
 4   num_market_pairs                  1000 non-null   int64
 5   date_added                        1000 non-null   object
 6   tags                              0 non-null      float64
 7   max_supply                        652 non-null    float64
 8   circulating_supply                1000 non-null   float64
 9   total_supply                      1000 non-null   float64
 10  cmc_rank                          1000 non-null   int64
 11  self_reported_circulating_supply  271 non-null    float64
 12  self_reported_market_cap          271 non-null    float64
 13  last_updated                      1000 non-null   object
 14  platform_id                       744 non-null    float64
 15  platform_name                     744 non-null    object
 16  platform_symbol                   744 non-null    object
 17  platform_slug                     744 non-null    object
 18  platform_token_address            744 non-null    object
 19  USD_price                         1000 non-null   float64
 20  USD_volume_24h                    1000 non-null   float64
 21  USD_volume_change_24h             1000 non-null   float64
 22  USD_percent_change_1h             1000 non-null   float64
 23  USD_percent_change_24h            1000 non-null   float64
 24  USD_percent_change_7d             1000 non-null   float64
 25  USD_percent_change_30d            1000 non-null   float64
 26  USD_percent_change_60d            1000 non-null   float64
 27  USD_percent_change_90d            1000 non-null   float64
 28  USD_market_cap                    1000 non-null   float64
 29  USD_market_cap_dominance          1000 non-null   float64
 30  USD_fully_diluted_market_cap      1000 non-null   float64
 31  USD_last_updated                  1000 non-null   object
dtypes: float64(19), int64(3), object(10)
memory usage: 250.1+ KB

In [7]:
crypto.shape

(1000, 32)

In [4]:
crypto.describe()

,id,num_market_pairs,tags,max_supply,circulating_supply,total_supply,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,platform_id,...,USD_volume_change_24h,USD_percent_change_1h,USD_percent_change_24h,USD_percent_change_7d,USD_percent_change_30d,USD_percent_change_60d,USD_percent_change_90d,USD_market_cap,USD_market_cap_dominance,USD_fully_diluted_market_cap
count,1000.000000,1000.000000,0.0,6.520000e+02,1.000000e+03,1.000000e+03,1000.000000,2.710000e+02,2.710000e+02,744.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1.000000e+03
mean,6079.453000,96.204000,NaN,1.713627e+15,1.084328e+15,1.144077e+15,500.500000,2.416846e+20,3.065988e+20,1364.052419,...,27.315816,0.317597,-3.385450,-14.310225,-2.027784,59.456706,37.812120,1.783902e+09,0.100007,1.006277e+12
std,3510.119482,983.350707,NaN,3.935331e+16,3.111962e+16,3.123662e+16,288.819436,3.978631e+21,5.047253e+21,900.862994,...,175.338227,2.094012,4.972479,66.436701,47.543025,2442.227800,1472.467545,2.509303e+10,1.473936,3.168158e+13
min,1.000000,1.000000,NaN,0.000000e+00,3.020000e+02,0.000000e+00,1.000000,4.845000e+04,4.028959e+05,512.000000,...,-100.000000,-27.711562,-31.220043,-64.632632,-74.028108,-92.808892,-96.840513,8.513606e+06,0.000000,0.000000e+00
25%,3138.500000,8.000000,NaN,1.000000e+08,3.605617e+07,9.650265e+07,250.750000,2.220290e+07,1.803590e+07,1027.000000,...,-16.795300,-0.029854,-5.808324,-23.156491,-17.752333,-51.845243,-62.760309,2.120246e+07,0.000000,4.694799e+07
50%,5623.500000,18.000000,NaN,8.053600e+08,1.884509e+08,5.000000e+08,500.500000,1.220276e+08,5.071718e+07,1027.000000,...,1.119550,0.280647,-3.167161,-17.825553,-5.298599,-40.678147,-51.024478,5.372393e+07,0.000000,1.539231e+08
75%,8410.000000,42.000000,NaN,3.052757e+09,1.067364e+09,2.211891e+09,750.250000,1.523807e+09,1.313688e+08,1027.000000,...,21.732225,0.703096,-0.960072,-11.631153,3.835519,-26.038310,-31.419881,1.830482e+08,0.007225,5.584541e+08
max,18112.000000,28381.000000,NaN,1.000000e+18,9.818477e+17,9.818477e+17,1000.000000,6.549654e+22,8.308827e+22,5805.000000,...,2883.113400,28.842421,45.965901,2040.834060,1007.909580,75920.567510,34464.875434,7.182518e+11,42.204700,1.001863e+15

## Melihat Keanehan Data
Pada data tersebut saya melihat beberapa keanehan:
<ul>
<li>Nilai Tags kosong tidak memiliki nilai</li>
<li>ada missing value pada kolom max_supply yaitu 348</li>
<li>missing value pada self_reported_circulating_supply dan self_reported_market_cap yaitu 729</li>
<li>dan missing value pada platform_id, platform_name, platform_symbol, platform_slug, platform_token_address yaitu sebanyak 256</li>
</ul>

<p>Untuk mengatasi masalah ini saya akan menghapus pada kolom tags dan mengatasi missing value dengan nilai rata-rata pada sisanya</p>

### Mengatasi Missing Value Menghapus Colom tags

In [15]:
crypto = crypto.drop(columns=['tags'])

crypto.shape

(1000, 31)

In [16]:
crypto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 31 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                1000 non-null   int64
 1   name                              1000 non-null   object
 2   symbol                            1000 non-null   object
 3   slug                              1000 non-null   object
 4   num_market_pairs                  1000 non-null   int64
 5   date_added                        1000 non-null   object
 6   max_supply                        652 non-null    float64
 7   circulating_supply                1000 non-null   float64
 8   total_supply                      1000 non-null   float64
 9   cmc_rank                          1000 non-null   int64
 10  self_reported_circulating_supply  271 non-null    float64
 11  self_reported_market_cap          271 non-null    float64
 12  last_updated                      1000 non-null   object
 13  platform_id                       744 non-null    float64
 14  platform_name                     744 non-null    object
 15  platform_symbol                   744 non-null    object
 16  platform_slug                     744 non-null    object
 17  platform_token_address            744 non-null    object
 18  USD_price                         1000 non-null   float64
 19  USD_volume_24h                    1000 non-null   float64
 20  USD_volume_change_24h             1000 non-null   float64
 21  USD_percent_change_1h             1000 non-null   float64
 22  USD_percent_change_24h            1000 non-null   float64
 23  USD_percent_change_7d             1000 non-null   float64
 24  USD_percent_change_30d            1000 non-null   float64
 25  USD_percent_change_60d            1000 non-null   float64
 26  USD_percent_change_90d            1000 non-null   float64
 27  USD_market_cap                    1000 non-null   float64
 28  USD_market_cap_dominance          1000 non-null   float64
 29  USD_fully_diluted_market_cap      1000 non-null   float64
 30  USD_last_updated                  1000 non-null   object
dtypes: float64(18), int64(3), object(10)
memory usage: 250.0+ KB

Disini Kita berhasil untuk menghapus kolom tags(dihapus Karena tidak seluruh kolom tidak ada nilainya dan bisa dianggap tidak berpengaruu)

## Mengatasi Missing Value pada column
<ul>
<li>max_supply</li>
<li>self_reported_circulating_supply</li>
<li>self_reported_market_cap</li>
<li>platform_id</li>
<li>platform_name</li>
<li>platform_symbol</li>
<li>platform_slug</li>
<li>platform_token_address</li>
</ul>

In [17]:
print(crypto.isnull().sum())

id                                    0
name                                  0
symbol                                0
slug                                  0
num_market_pairs                      0
date_added                            0
max_supply                          348
circulating_supply                    0
total_supply                          0
cmc_rank                              0
self_reported_circulating_supply    729
self_reported_market_cap            729
last_updated                          0
platform_id                         256
platform_name                       256
platform_symbol                     256
platform_slug                       256
platform_token_address              256
USD_price                             0
USD_volume_24h                        0
USD_volume_change_24h                 0
USD_percent_change_1h                 0
USD_percent_change_24h                0
USD_percent_change_7d                 0
USD_percent_change_30d                0
USD_percent_change_60d                0
USD_percent_change_90d                0
USD_market_cap                        0
USD_market_cap_dominance              0
USD_fully_diluted_market_cap          0
USD_last_updated                      0
dtype: int64

Dilihat dari jumlah nilai yang hilang disana jumlahnya terlalu banyak dan jika kita menghapusnya akan berdampak pada akurasi prediksi<br>
pada data itu terdapat 4 column yang memiliki datatype numeric <br>
dan 4 data yang memiliki datatype catagorical

### Mengatasi missing value pada katagori colum

In [19]:
missing_categorical = crypto.select_dtypes(include=['object']).isnull().sum()

missing_categorical = missing_categorical[missing_categorical > 0]

print(missing_categorical)

platform_name             256
platform_symbol           256
platform_slug             256
platform_token_address    256
dtype: int64

Disini saya mengatasinya dengan metode modus, yaitu mengisi nilai kosong dengan nilai yang sering keluar.

In [20]:
for col in ['platform_name', 'platform_symbol', 'platform_slug', 'platform_token_address']:
    crypto[col].fillna(crypto[col].mode()[0], inplace=True)

<ipython-input-20-f0c122505fdc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  crypto[col].fillna(crypto[col].mode()[0], inplace=True)

In [22]:
print(crypto.isnull().sum())

id                                    0
name                                  0
symbol                                0
slug                                  0
num_market_pairs                      0
date_added                            0
max_supply                          348
circulating_supply                    0
total_supply                          0
cmc_rank                              0
self_reported_circulating_supply    729
self_reported_market_cap            729
last_updated                          0
platform_id                         256
platform_name                         0
platform_symbol                       0
platform_slug                         0
platform_token_address                0
USD_price                             0
USD_volume_24h                        0
USD_volume_change_24h                 0
USD_percent_change_1h                 0
USD_percent_change_24h                0
USD_percent_change_7d                 0
USD_percent_change_30d                0
USD_percent_change_60d                0
USD_percent_change_90d                0
USD_market_cap                        0
USD_market_cap_dominance              0
USD_fully_diluted_market_cap          0
USD_last_updated                      0
dtype: int64

Bisa Dilihat Data yang katagorikal tadi sudah bersih dilihat dari data di atas

### Mengatasi missing value pada numeric colum

In [24]:
missing_categorical = crypto.select_dtypes(include=['number']).isnull().sum()

missing_categorical = missing_categorical[missing_categorical > 0]

print(missing_categorical)

max_supply                          348
self_reported_circulating_supply    729
self_reported_market_cap            729
platform_id                         256
dtype: int64

Disini karena data bertype numeric saya akan menggunakan metode median yaitu mengisi nilai yang kosong dengan nilai median dari column tersebut

In [25]:
for col in ['max_supply', 'self_reported_circulating_supply', 'self_reported_market_cap', 'platform_id']:
    crypto[col].fillna(crypto[col].median(), inplace=True)

<ipython-input-25-ff8fe281f9c7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  crypto[col].fillna(crypto[col].median(), inplace=True)

In [26]:
print(crypto.isnull().sum())

id                                  0
name                                0
symbol                              0
slug                                0
num_market_pairs                    0
date_added                          0
max_supply                          0
circulating_supply                  0
total_supply                        0
cmc_rank                            0
self_reported_circulating_supply    0
self_reported_market_cap            0
last_updated                        0
platform_id                         0
platform_name                       0
platform_symbol                     0
platform_slug                       0
platform_token_address              0
USD_price                           0
USD_volume_24h                      0
USD_volume_change_24h               0
USD_percent_change_1h               0
USD_percent_change_24h              0
USD_percent_change_7d               0
USD_percent_change_30d              0
USD_percent_change_60d              0
USD_percent_change_90d              0
USD_market_cap                      0
USD_market_cap_dominance            0
USD_fully_diluted_market_cap        0
USD_last_updated                    0
dtype: int64

In [27]:
crypto.shape

(1000, 31)